name: 03 - Workflow Runners
on: workflow_dispatch
jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS with runner.os
        run: |
          echo "This job is running on an Ubuntu runner"
          echo "Runner OS: ${{ runner.os }} runner"
      - name: Show OS with RUNNER_OS
        run: |
          echo "This job is running on an Ubuntu runner"
          echo "Runner OS: $RUNNER_OS runner"
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
        run: |
          echo "This job is running on an Windows runner"
          echo "Runner OS: $RUNNER_OS"
