name: 10 - Execution Flow
on:
  workflow_dispatch:
    inputs:
      pass-unit-tests:
        type: boolean
        description: "Whether unit tests will pass or not"
        default: true
jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Lint code
        run: echo "Linting and building project"
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: echo "Running unit tests..."
      - name: Failing tests
        if: ${{ !inputs.pass-unit-tests }}
        run: exit 1
  deploy-nonprod:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to nonprod
        run: echo "Deploying to nonprod..."
    needs:
      - lint-build
      - unit-tests
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run E2E tests
        run: echo "Running E2E tests..."
    needs:
      - deploy-nonprod
  load-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run load tests
        run: echo "Running load tests..."
    needs:
      - deploy-nonprod
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to prod
        run: echo "Deploying to prod..."
    needs:
      - e2e-tests
      - load-tests
